### ISSUE TITLE
Difficulties in getting RGB-D Camera information

### ISSUE THREAD

**Issue by RBastos36** [Goncalo287/savi_t2#7]
Not being able to get depth information from the camera being used (Orbbec), only being able to get RGB values. Tried using OpenCV library (supposedly has a function to get information from RGB-D cameras) to get said information but with no success.

**Comment by AdrianoFF10** [comment]
Maybe try to use the information in this [site](https://astra-wiki.readthedocs.io/en/latest/examples.html), where is displayed information about Orbbec Astra and how to configure it.

You can also check if this [site](https://opencv.org/blog/working-with-orbbec-astra-3d-cameras-using-opencv/) is useful, but the information is in C++.

There is also a script that converts a RGB and a depth image into a PointCloud [here](https://github.com/Goncalo287/savi_t2/blob/main/Part6/Test1.py).

**Comment by Goncalo287** [comment]
It's working, the program shows the color and depth image with opencv. The depth image is obtained using [OpenNI](https://astra-wiki.readthedocs.io/en/latest/installation.html#linux). When the user presses "enter" to confirm, it generates a point cloud from those images and uses it as a scene. The clustering parameters are different for these scenes since there are fewer points (only uses 1 image to generate the point cloud).
